name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup-node:
    name: Set up Node.js
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

  deploy-hw1:
    name: Deploy hw1
    runs-on: ubuntu-latest
    needs: setup-node

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change to hw1 directory
        run: cd hw1

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
